Traceback (most recent call last):
  File "/home/s2244487/Machine-Learning-Systems/task-1/task.py", line 1209, in <module>
    test_kmeans_1000_2()
  File "/home/s2244487/Machine-Learning-Systems/task-1/task.py", line 846, in test_kmeans_1000_2
    N, D, A, K = testdata_kmeans("1000_2_meta.json")
  File "/home/s2244487/Machine-Learning-Systems/task-1/test.py", line 31, in testdata_kmeans
    A = np.loadtxt(A_file)
  File "/home/s2244487/.conda/envs/mlsys/lib/python3.10/site-packages/numpy/lib/_npyio_impl.py", line 1395, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/s2244487/.conda/envs/mlsys/lib/python3.10/site-packages/numpy/lib/_npyio_impl.py", line 1046, in _read
    arr = _load_from_filelike(
  File "/home/s2244487/.conda/envs/mlsys/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
