Traceback (most recent call last):
  File "/home/s2244487/Machine-Learning-Systems/task-1/task.py", line 1209, in <module>
    test_kmeans_1000_2()
  File "/home/s2244487/Machine-Learning-Systems/task-1/task.py", line 853, in test_kmeans_1000_2
    _, gpu_time = measure_time(our_kmeans, N, D, A, K, plot)
  File "/home/s2244487/Machine-Learning-Systems/task-1/task.py", line 643, in measure_time
    result = func(*args, **kwargs)
TypeError: our_kmeans() takes 4 positional arguments but 5 were given
